### ISSUE TITLE
'NoneType' object has no attribute 'ctrl_transfer'

### ISSUE THREAD

**Issue by Lunaphied** [Qyriad/python-usbreq#1]
I was trying to make a control transfer on a device that at some point disconnected: 
```
Lunaphied@Mira ~ @ dev.control_request(direction=usbreq.USBDirection.IN, req_type=usbreq.USBRequestType.VENDOR, recipient=usbreq.USBRecipient.DEVICE, request=0)
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/xonsh/0.14.0/libexec/lib/python3.11/site-packages/usbreq/__init__.py", line 471, in control_request
    return bytes(self.ctrl_transfer(bmRequestType=bmRequestType, bRequest=bRequest,
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xonsh/0.14.0/libexec/lib/python3.11/site-packages/usbreq/__init__.py", line 324, in __getattr__
    return getattr(self.dev, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ctrl_transfer'
```

Despite unplugging and replugging the device, along with attempting to get the device using `usbreq.find()`, I get the same error. `usbreq.find()` works successfully, but I can't make requests on the device.

**Comment by Qyriad** [comment]
Oh that's weird

**Comment by Qyriad** [comment]
I'll look at that in a bit. Is than on macOS or Linux?

**Comment by Lunaphied** [comment]
macOS

**Comment by Qyriad** [comment]
Oh wait it says /opt/homebrew right there :woman_facepalming:

**Comment by Lunaphied** [comment]
All good, Homebrew technically runs on Linux anyways

**Comment by Qyriad** [comment]
Huh. This isn't happening on my machine — can you post the repr/print of `dev.dev` when that happens? And can you also set `$LIBUSB_DEBUG = 255` and post the output of that? (Including the `usbreq.find()`)

**Comment by Lunaphied** [comment]
Managed to reproduce, this time without even unplugging. Seems like there's a few confusing behaviors going on here (like not picking the right device?) but the original behavior is visible as well
[iTerm2 Session Aug 31, 2023 at 13:40:26.txt](https://github.com/Qyriad/python-usbreq/files/12489740/iTerm2.Session.Aug.31.2023.at.13.40.26.txt)

**Comment by Lunaphied** [comment]
Okay seems like this one is on me. I didn't realize that `usbreq.find()` might return a `USBDevice` without it actually having found anything, nor that it wouldn't return a list in case of multiple devices found and I apparently used both the wrong arguments and wrong PID during my initial run.

[iTerm2.Session.Aug.31.2023.at.13.40.26.txt](https://github.com/Qyriad/python-usbreq/files/12489910/iTerm2.Session.Aug.31.2023.at.13.40.26.txt)
Here's the log I got with it working successfully

**Comment by Qyriad** [comment]
Ah, we should definitely handle `usb.core.find()` returning `None` or a generator better

**Comment by Lunaphied** [comment]
I certainly found the behavior of returning a random single device when no parameters are given as unexpected. Maybe it should be a slightly less thin wrapper over `usb.core.find()` so it can provide better ergonomics?

I'd also suggest documenting the parameters it takes more directly, since `usb.core.find()` isn't really well documented and the missing docs makes it a bit harder to use usbreq.

**Comment by Qyriad** [comment]
Documenting PyUSB's parameters here would be good yes. As for `None` and the generator behavior, I pushed 03835f5133771d712c2e40ec02541b33f7d143b1 — can you verify that fixes that part?

**Comment by Lunaphied** [comment]
I can confirm it fixes that part of the issue

**Comment by Qyriad** [comment]
Gotcha, I'll close this in favor of #2 then
